# Dockerfile

FROM debian:bullseye
RUN apt-get update
RUN apt-get install -y systemd systemd-sysv dbus dbus-user-session init
RUN ln -sf /lib/systemd/systemd /usr/sbin/init
COPY chrony /etc/default/chrony
COPY chronyd /etc/sysconfig/chronyd
